install.packages("tidyverse")
install.packages('INLA', repos='https://inla.r-inla-download.org/R/stable')
install.packages("SpatialEpi")
install.packages("cowplot")
install.packages("patchwork")
install.packages("viridis")
install.packages("knitr")
install.packages("kableExtra")
install.packages("inlabru")
install.packages("ggmap")
install.packages("patchwork")
