install.packages("tidyverse")
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
install.packages("SpatialEpi")
install.packages("cowplot")
install.packages("patchwork")
install.packages("viridis")
install.packages("knitr")
install.packages("kableExtra")
install.packages("inlabru")
install.packages("ggmap")
install.packages("patchwork")
install.packages("RColorBrewer")
install.packages("mapdata")
install.packages("maptools")
install.packages("mapview")
install.packages("rgdal")
install.packages("sf")
install.packages("sp")
install.packages("spdep")

